steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--file=docker/prod.Dockerfile'
      - '--tag=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$SHORT_SHA'
      - '.'
    id: 'build'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$SHORT_SHA']
    id: 'push'
images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: asia-south1
  _REPO_NAME: cloud-run-source-deploy
  _IMAGE_NAME: care
