name: Deploy Care

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - develop
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-gcr:
    name: Build and Push to GCR linux/amd64
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          platform=linux/amd64
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Generate docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            gcr.io/${{ secrets.GCR_PROJECT_ID }}/${{ github.repository }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-${{ runner.arch }}-buildx-prod-${{ hashFiles('Pipfile.lock', 'docker/prod.Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-buildx-prod-

      - name: Create new cache
        run: |
          mkdir -p ${{ runner.temp }}/.buildx-cache
          mkdir -p ${{ runner.temp }}/.buildx-cache-new

      - name: Build and push to GCR
        id: build-gcr
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/prod.Dockerfile
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,push=true
          build-args: |
            APP_VERSION=${{ github.sha }}
            ADDITIONAL_PLUGS=${{ env.ADDITIONAL_PLUGS }}
            BUILD_NUMBER=${{ github.run_number }}
          tags: |
            gcr.io/${{ secrets.GCR_PROJECT_ID }}/${{ github.repository }}:latest-${{ github.run_number }}
            gcr.io/${{ secrets.GCR_PROJECT_ID }}/${{ github.repository }}:sha-${{ github.sha }}
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build-gcr.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

      - name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache

  deploy-google-cloud-run:
    needs: build-gcr
    if: github.ref == 'refs/heads/develop'
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          CLOUDSDK_COMPUTE_REGION: ${{ secrets.GCP_REGION }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Decode Base64 env-vars and save to file
        run: |
          echo "${{ secrets.BASE64 }}" | base64 --decode > env.yaml


      - name: Deploy celery beat
        run: |
          gcloud run deploy celery-beat \
            --image gcr.io/${{ secrets.GCR_PROJECT_ID }}/${{ github.repository }}:latest-${{ github.run_number }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8000 \
            --command="/app/celery_beat-gcr.sh" \
            --env-vars-file=env.yaml \
            --memory 512Mi

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy celery-worker \
            --image gcr.io/${{ secrets.GCR_PROJECT_ID }}/${{ github.repository }}:latest-${{ github.run_number }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8000 \
            --command="/app/start.sh" \
            --env-vars-file=env.yaml \
            --memory 512Mi

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy care-backend \
            --image gcr.io/${{ secrets.GCR_PROJECT_ID }}/${{ github.repository }}:latest-${{ github.run_number }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 9000 \
            --command="/app/start.sh" \
            --env-vars-file=env.yaml \
            --memory 512Mi
